### ISSUE TITLE
CSS font-family definitions don't define fallbacks

### ISSUE THREAD

**Issue by jahed** [RMerl/asuswrt-merlin.ng#215]
I noticed after switching to GNU/Linux that the web interface's fonts aren't falling back correctly. The most obvious one is the sidebar, which is set to:

```css
.menu {
  font-family: Verdana;
}
```

This means when Verdana isn't available by default it will fall back to the browser's default serif font. Verdana is a sans-serif font, so seeing serif (usually Times New Roman or some variant) makes the interface look odd.

The fix is simple:

```css
.menu {
  font-family: Verdana, sans-serif;
}
```

I can send a PR to fix this across all the stylesheets, but before I do, I'm wondering if style fixes are within the scope of Merlin.
