### ISSUE TITLE
DNS-over-TLS fails sometimes

### ISSUE THREAD

**Issue by n76** [RMerl/asuswrt-merlin.ng#566]
Firmware: 384.18
Hardware: RT-AC1900P
Configured DNS-over-IP servers: 
2606:4700:4700::1111    cloudflare-dns.com
1.1.1.1    cloudflare-dns.com
1.0.0.1    cloudflare-dns.com
2606:4700:4700::1001    cloudflare-dns.com

DNS servers picked using "Preset servers" drop down.

On a computer within the LAN try a lookup for a DNS name that returns a large number of A records. Results vary, but for Linux based I sometimes get this:
```
$ nslookup archive.raspberrypi.org
;; connection timed out; no servers could be reached
```
and other times I get this:
```
$ nslookup archive.raspberrypi.org
;; Truncated, retrying in TCP mode.
;; communications error to 10.7.52.1#53: connection reset
```
On a MacOS I get:
```
$ nslookup archive.raspberrypi.org
;; Truncated, retrying in TCP mode.
;; communications error to xxxx:xxxx:4000:30::1#53: connection reset
```

With DNS-over-TLS turned off I get successful response on both platforms with quite a few entries:
```
$ nslookup archive.raspberrypi.org | grep Address | wc -l
25
```
I suspect a buffer size issue someplace.

---
Edit: Looks like the DNS-over-TLS configuration is saved in /etc/stubby/stubby.yml Here is the contents if that helps show my configuration:

```

admin@RT-AC1900P-7A10:/tmp/etc/stubby# cat stubby.yml 
resolution_type: GETDNS_RESOLUTION_STUB
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 128
appdata_dir: "/var/lib/misc"
resolvconf: "/tmp/resolv.conf"
edns_client_subnet_private: 1
round_robin_upstreams: 1
idle_timeout: 9000
tls_connection_retries: 2
tls_backoff_time: 900
timeout: 3000
listen_addresses:
  - 127.0.1.1@53
upstream_recursive_servers:
  - address_data: 2606:4700:4700::1111
    tls_auth_name: "cloudflare-dns.com"
  - address_data: 1.1.1.1
    tls_auth_name: "cloudflare-dns.com"
  - address_data: 1.0.0.1
    tls_auth_name: "cloudflare-dns.com"
  - address_data: 2606:4700:4700::1001
    tls_auth_name: "cloudflare-dns.com"
admin@RT-AC1900P-7A10:/tmp/etc/stubby# 
```
